version: '3.1'

services:
  chatgpt-4o-db:
    container_name: chatgpt-4o-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: chatgpt_4o_user
      POSTGRES_PASSWORD: strongUserPassword
      POSTGRES_DB: chatgpt_4o
    volumes:
      - ./db-volume:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"